!Configuration
energyService: default
EASCName: EASC-CSUC
energisExecutePort: 8080
energisExecuteURL: hackmeplz
energisPort: 9999
energisURL: hackmeplz
monitoringSamplingTime: !amount '300 s'
siteCode: csuc_barcelona
