!Configuration
EASCName: easc_hp
energyService: default
energisExecutePort: 8080
energisExecuteURL: hackmeplz
energisPort: 9999
energisURL: hackmeplz
monitoringSamplingTime: !amount '300 s'
siteCode: hp_milan
