!Configuration
EASCName: EASC-IaaS
energyService: default
port: 9999
energisExecutePort: 8080
energisExecuteURL: hackmeplz
energisPort: 9999
energisURL: hackmeplz
monitoringSamplingTime: !amount '300 s'
siteCode: hp_milan
