!Configuration
energyService: shared-infrastructure 
EASCName: EASC1
energisExecutePort: 8080
energisExecuteURL: hackmeplz
energisPort: 9999
energisURL: hackmeplz
monitoringSamplingTime: !amount '30 s'
siteCode: cn_trento
