!Configuration
energyService: default
EASCName: EASC-Trento
energisExecutePort: 8080
energisExecuteURL: hackmeplz
energisPort: 9999
energisURL: hackmeplz
monitoringSamplingTime: !amount '300 s'
siteCode: cn_trento

