#!/usr/bin/env Rscript
library(ggplot2)
library(reshape2)
library(plyr)

# Parse command line arguments.
args <- commandArgs(trailingOnly = TRUE)

# Read forecasts.csv generated by Statistics.java on cs-bench project.
forecasts <- read.table(paste(args[1],"/forecasts.csv", sep=""), sep=";", quote="\"", header=T, stringsAsFactors = FALSE)

# Read eascs.csv generated by Statistics.java on cs-bench project.
easc <- read.table(paste(args[1],"/eascs.csv",sep=""), sep=";", quote="\"", header=T, stringsAsFactors = FALSE)

# Adapt forecasts column name to merge tables correctly.
forecasts <- rename(forecasts, c("dc"="datacenter"))

# Sum the power used at each timeslot.
power <-
  ddply(
    forecasts, .(slot, datacenter), 
    function(x) {
      # Preserve some parameters.
      slot = x$slot
      datacenter = x$datacenter
      source = x$source
      capacity = x$capacity
      renPct = x$renPct
      
      # Easc subset, datacenter, slot.
      easc.subset = easc[(
        (easc$slot == slot) & 
        (easc$datacenter == datacenter)),
      ]
      
      # Sum the total power used at each timeslot.
      watts = sum(easc.subset$watts)
      
      time <- easc.subset$time[1]
      
      newdf <- data.frame(slot, datacenter, source, capacity, renPct, time, watts)
      newdf
    }
  )

# Compute the usedRenewable from all power sources.
# Min(renewableAvailable, powerRequired)
power$usedPureRenew <- pmin(power$capacity*power$renPct/100, power$watts)

# Correct the usedRenewable amount from grid, considering only what was not used with other sources. 
# Only if there is pure green energy sources.
if ( any(!grepl("grid", power$source)) ) {
  power[grep("grid", power$source),]$usedPureRenew <- 
    pmax(0, 
      power[!grepl("grid", power$source),]$watts -
      power[!grepl("grid", power$source),]$usedPureRenew
    ) * 
    power[grep("grid", power$source),]$renPct/100
  
  # Now need to summarise summing used renewable from different sources.
  powerRenewable <- ddply(power[!grepl("grid",power$source, perl=TRUE),], .(time, datacenter), summarise, POW=sum(usedPureRenew))
  powerRenewable$type = "renewable"
}else {
  powerRenewable <- ddply(power, .(time, datacenter), summarise, POW=sum(watts*renPct/100))
  powerRenewable$type <- "renewable"
}

# Power total used is directly the power from eascs.csv file.
powerTotal <- ddply(power[grep("grid", power$source),], .(time, datacenter), summarise, POW=sum(watts))

# Create a label to differenciate POW of renewables and total.
powerTotal$type <- "total"

# Finally build a dataframe where POW is the used power and type ("total" or "renewable")
# indicates the type.
power <- rbind(powerTotal, powerRenewable)

# Correctly parse date and time to R format. 
# NOTE: need to do this after any ddply call to avoid bizarre error.
power$time <- strptime(power$time, "%Y-%m-%dT%H:%M:%S.000")

# Rename to improve graph readability.
power <- rename(power, c("POW"="power"))

# Show one graph per datacenter of power usage, renewable, and total available 
p <- ggplot(data = power, aes(x = time, y = power, color = type)) +
  geom_line(aes(group = type))

# Add facets if there are multiple datacenters.
if (length(unique(power$datacenter)) > 1) {
  p <- p + facet_wrap(~ datacenter, scales="free_y")
}

#Write the mean ren percent in a file
write(paste("ren percent with DC4Cities=", 100 * sum(powerRenewable$POW) / sum(powerTotal$POW), "%"),
      file = paste(args[1],"/DC4CitiesRenPct.txt",sep=""))


# Enhance graph using bw theme, clean axis title, and 
# rotate 45 degree x-axis labels. 
p <- p + theme_bw() +
  theme(legend.position="top", axis.title.x = element_blank()) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
  
# Generate a pdf file.
ggsave(paste(args[1],"/power.pdf",sep=""), width=6, height=3)
# Generate also a png file, more web friendly to show report on jenkings.
ggsave(paste(args[1],"/power.png",sep=""), width=6, height=3)