#!/usr/bin/env Rscript
##################################################################################
# 
# Script that generates graphs for each datacenter showing the power consumption 
# at each timeslot. This script uses facet_wrapt which may difficult 
# visualiasation with more than 3 datacenters existe. This is not a big flaw since
# the script main design goal is to provide a continuous integration report to
# speed the development of DC4Cities.
#
##################################################################################
library("ggplot2")
library("reshape2")
library("plyr")

# Parse command line arguments.
args <- commandArgs(trailingOnly = TRUE)

# Read eascs.csv generated by Statistics.java on cs-bench project.
easc <- read.table(paste(args[1],"/eascs.csv",sep=""), sep=";", quote="\"", header=T)

#create a column to have unique na  mes of activities concatenated to the easc name
easc$activity <- paste(easc$easc, easc$activity, sep=":")

#correctly parse date and time to R format
easc$time <- strptime(easc$time, "%Y-%m-%dT%H:%M:%S.000")

#create a graph where each activity is a unique line per datacenter
p <- ggplot(data = easc, aes(x = time, y = watts)) +
  geom_area(aes(colour=activity, fill=activity), position='stack')

  if (length(unique(easc$datacenter)) > 1) {
    p <- p + facet_wrap(~ datacenter, scales="free_y")
  }

p <- p +  theme_bw() +
theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
theme(legend.position="top", axis.title.x = element_blank())


#finally generate the image file in pdf, this is converted in png by the 
# post build script that generates also generate the html file for viewing the
# report.
ggsave(paste(args[1],"/power_per_datacenter.pdf",sep=""), width=10, height=3)
ggsave(paste(args[1],"/power_per_datacenter.png",sep=""), width=10, height=3)




