#!/usr/bin/env Rscript
library(ggplot2)
library(reshape2)
library(plyr)

# Parse command line arguments.
args <- commandArgs(trailingOnly = TRUE)

# Read forecasts.csv generated by Statistics.java on cs-bench project.
forecasts <- read.table(paste(args[1],"/forecasts.csv", sep=""), sep=";", quote="\"", header=T, stringsAsFactors = FALSE)

# Read eascs.csv generated by Statistics.java on cs-bench project.
easc <- read.table(paste(args[1],"/eascs.csv",sep=""), sep=";", quote="\"", header=T, stringsAsFactors = FALSE)

# Adapt forecasts column name to merge tables correctly.
forecasts <- rename(forecasts, c("dc"="datacenter"))

# Sum the power used at each timeslot.
power <-
  ddply(
    forecasts, .(slot, datacenter), 
    function(x) {
      # Preserve some parameters.
      slot = x$slot
      datacenter = x$datacenter
      source = x$source
      capacity = x$capacity
      renPct = x$renPct
      
      # Easc subset, datacenter, slot.
      easc.subset = easc[(
        (easc$slot == slot) & 
          (easc$datacenter == datacenter)),
        ]
      
      # Sum the total power used at each timeslot.
      watts = sum(easc.subset$watts)
      
      time <- easc.subset$time[1]
      
      newdf <- data.frame(slot, datacenter, source, capacity, renPct, time, watts)
      newdf
    }
  )

# Filter to ignore non-pure power sources.
power <- power[ (!grepl("grid", power$source)), ]

# Compute the usedRenewable from all power sources.
# Min(renewableAvailable, powerRequired)
power$usedPureRenew <- pmin(power$capacity*power$renPct/100, power$watts)

# Compute the waste of renewable by the usedRenew - capacity, aggregate summing by slot,dc.
power$RenewablePowerWaste <- power$capacity - power$usedPureRenew

# Correctly parse date and time to R format. 
# NOTE: need to do this after any ddply call to avoid bizarre error.
power$time <- strptime(power$time, "%Y-%m-%dT%H:%M:%S.000+01:00")

# Show one graph per datacenter of power usage, renewable, and total available 
#create a graph where each activity is a unique line per datacenter
p <- ggplot(data = power, aes(x = time, y = RenewablePowerWaste, color = source)) +
  geom_line(aes(group = source))

# Add facets if there are multiple datacenters.
if (length(unique(power$datacenter)) > 1) {
  p <- p + facet_wrap(~ datacenter, scales="free_y")
}

# Enhance graph using bw theme, clean axis title, and 
# rotate 45 degree x-axis labels. 
p <- p +  theme_bw() +
  theme(legend.position="top", axis.title.x = element_blank()) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(y = "watts")

# Generate a pdf file.
ggsave(paste(args[1],"/renewable-waste.pdf",sep=""), width=3 * length(unique(power$datacenter)), height=3)
# Generate also a png file, more web friendly to show report on jenkings.
ggsave(paste(args[1],"/renewable-waste.png",sep=""), width=3 * length(unique(power$datacenter)), height=3)
